### ISSUE TITLE
A Couple of UI Comments

### ISSUE THREAD

**Issue by SteveFeldman** [jleo32/VehicleMPG#2]
Justin,

A couple of quick comments about the UI. These are really small comments and just simple improvements to consider...
1. Would it be possible to demonstrate a couple of visualizations? A possible toggle between chart types would suffice.
2. The current chart would benefit by putting the Y-axis to the left. Having it aligned to the right makes it difficult to read. In fact, I didn't realize it was there until I ended up scrolling.

Regards,

Steve

**Comment by jleo32** [comment]
I have a slight redesign in mind since my friend set me a link to dribbble.com for some inspiration.

That will allow for better space to add more visualizations. I agreed a toggle would be good.

Agreed, Y axis on the left makes sense. Sorry for the scroll. I use a 1440p monitor so sometimes what I make looks different on other resolutions. I'm going to look into a more responsive approach to the charts.

Thank you.
